[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_hello_world = "CBxLiSGTZzrVxR4fD4HUAe8sNqXT9qv6yHDh9nLShSpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kalasag/.config/solana/genesis.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
